### ISSUE TITLE
cannot import name 'block_extractor_cuda'

### ISSUE THREAD

**Issue by sanazsab** [cuiaiyu/dressing-in-order#20]
Hi,

This error pops up: ImportError: cannot import name 'block_extractor_cuda'

I do not know that is it because the .cc format or others and what should I do next?

Bad key "text.kerning_factor" on line 4 in
/Midgard/home/sanazsab/miniconda3/envs/gfla/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Traceback (most recent call last):
  File "train.py", line 125, in <module>
    main()
  File "train.py", line 34, in main
    opt = TrainOptions().parse()   # get training options
  File "/Midgard/home/sanazsab/virtual-tryon/dressing-in-order/options/base_options.py", line 116, in parse
    opt = self.gather_options()
  File "/Midgard/home/sanazsab/virtual-tryon/dressing-in-order/options/base_options.py", line 76, in gather_options
    model_option_setter = models.get_option_setter(model_name)
  File "/Midgard/home/sanazsab/virtual-tryon/dressing-in-order/models/__init__.py", line 47, in get_option_setter
    model_class = find_model_using_name(model_name)
  File "/Midgard/home/sanazsab/virtual-tryon/dressing-in-order/models/__init__.py", line 30, in find_model_using_name
    modellib = importlib.import_module(model_filename)
  File "/Midgard/home/sanazsab/miniconda3/envs/gfla/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Midgard/home/sanazsab/virtual-tryon/dressing-in-order/models/flow_model.py", line 3, in <module>
    from models.networks.block_extractor.block_extractor import BlockExtractor
  File "/Midgard/home/sanazsab/virtual-tryon/dressing-in-order/models/networks/block_extractor/block_extractor.py", line 8, in <module>
    from block_extractor import block_extractor_cuda
ImportError: cannot import name 'block_extractor_cuda'

**Comment by cuiaiyu** [comment]
This question is about GFLA cuda function, which is a dependent library. We don't have too much insight and would suggest to ask in GFLA's repository.
